name: Build pingtunnel for Ubuntu amd64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Add this to enable manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Build for Ubuntu amd64
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o pingtunnel .

      - name: Verify binary
        run: |
          file ./pingtunnel
          ./pingtunnel -h

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: pingtunnel-ubuntu-amd64
          path: ./pingtunnel
          retention-days: 7
