name: Build pingtunnel for Ubuntu amd64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual runs via Run workflow button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libc6-dev # For potential CGO requirements

      - name: Clean workspace
        run: |
          rm -f pingtunnel
          ls -la

      - name: Install Go dependencies
        run: |
          go mod tidy || go get github.com/esrrhs/gohome@master

      - name: Build for Ubuntu amd64
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0 # Disable CGO unless required
        run: go build -v -o pingtunnel ./cmd/

      - name: Make binary executable
        run: chmod +x ./pingtunnel

      - name: Verify binary
        run: |
          ls -la ./pingtunnel
          file ./pingtunnel
          ./pingtunnel -h

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: pingtunnel-ubuntu-amd64
          path: ./pingtunnel
          retention-days: 7
